### ISSUE TITLE
Originator of the log message

### ISSUE THREAD

**Issue by ckmk14** [cisagov/icsnpp-s7comm#1]
# 🐛 Summary #

First of all, nice work! Very helpful. 
I encountered the same problem already in the s7comm-parser from amazon and described it [here](https://github.com/amzn/zeek-plugin-s7comm/issues/7)

## To reproduce ##

1. Parse e.g. the following [file ](https://github.com/gymgit/s7-pcaps/blob/master/snap7_s300_readVar.pcapng)
2. The following cotp.log is generated:

#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	cotp
#open	2022-05-12-00-01-54
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	pdu_code	pdu_name
#types	time	string	addr	port	addr	port	string	string
1397638799.789531	ChM6f83MB5grALIJgd	134.249.62.206	52446	134.249.61.163	102	0x0f	DT Data
1397638799.793176	ChM6f83MB5grALIJgd	134.249.62.206	52446	134.249.61.163	102	0x0f	DT Data
#close	2022-05-12-00-01-54

## Expected behavior ##

The first log entry was caused by 134.249.62.206 and the second one by 134.249.61.163. This is not clear by analyzing the log file. It would be nice, if an additional attribute (e..g. is_orig boolean value) identifies the originator of the message.

**Comment by mmguero** [comment]
@Kleinspider this was solved by #3 and i think can be closed
