### ISSUE TITLE
Zeek Version-Specific ProtocolViolation() and AnalyzerViolation() Conditional

### ISSUE THREAD

**Issue by jcyprus** [cisagov/icsnpp-s7comm#6]
# Summary #

Zeek has deprecated the `ProtocolViolation()` function that is used to throw exceptions in the
corresponding pac files for parsers for Zeek version >= 4.2. This change was accompanied by the
removal of `ProtocolViolation()` from all default Zeek parsers and `AnalyzerViolation()` taking its place.
`AnalyzerViolation()` is not backwards compatible, therefore to allow this parser to be used with versions
before and after 4.2, this parser has removed the violation handler altogether. This proposed fix
implements a C++ preprocessor conditional that choses the correct function based on the Zeek version
so the violation functionality can be restored.

## Motivation and Context ##

`ProtocolViolation()` and `AnalyzerViolation()` are useful functions to be used when packets are unable to
be delivered via the `DeliverStream()` function due to errors in the Zeek-received data. Zeek, instead of
exhibiting unexpected behavior, handles the data errors by throwing a standard exception for that
connection.

Since Zeek has officially deprecated `ProtocolViolation()`, parsers that contain that function will no longer
compile past Zeek 4.2. All prepackaged Zeek parsers have changed their violation function. To maintain
useability between versions < 4.2 and >= 4.2, this parser decided to remove the violation function
altogether in `commit 2c9f6dc`. While this achieved the goal of having the parser compile with 
multiple Zeek versions, it may have unintended consequences if the parser is faced with unexpected data.

## Fixes and Implementation Notes ##

The analyzer could use a C++ preprocessor conditional to choose which violation function to use based
on the Zeek version it is compiled with. It could do this by checking the current Zeek version against the
value 40200, which corresponds to Zeek version 4.02.00.

## Code Comparison Between Current Implementation and Proposed Fixes ##

```
Comparing files S7COMM.cc and S7COMM-WITH-FIXES.CC
***** S7COMM.cc
45: {
46: }
***** S7COMM-WITH-FIXES.CC
45: {
46: #if ZEEK_VERSION_NUMBER < 40200
47: ProtocolViolation(util::fmt("Binpac exception: %s", e.c_msg()));
48:
49: #else
50: AnalyzerViolation(util::fmt("Binpac exception: %s", e.c_msg()));
51:
52: #endif
53: }
*****
```

**Comment by Kleinspider** [comment]
Code changes as requested have been tested and pushed into main
